apiVersion: v1
kind: Pod
metadata:
  name: emptydir-demo
spec:
  containers:
  - name: writer
    image: busybox
    command:
      - /bin/sh
      - -c
    args:
      - |
        while true; do
          date >> /shared/time.txt
          sleep 5
        done
    volumeMounts:
      - name: shared-storage
        mountPath: /shared

  - name: reader
    image: busybox
    command:
      - /bin/sh
      - -c
    args:
      - |
        while true; do
          cat /shared/time.txt
          sleep 10
        done
    volumeMounts:
      - name: shared-storage
        mountPath: /shared

  volumes:
  - name: shared-storage
    emptyDir: {}
