apiVersion: v1
kind: Pod

metadata:
  name: nginx-config-demo

spec:
  containers:
    - name: nginx
      image: nginx:latest

      env:
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ENV

        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_NAME

        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOG_LEVEL
