apiVersion: v1
kind: Pod

metadata:
  name: nginx-secret-demo

spec:
  containers:
    - name: nginx
      image: nginx:latest

      env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
