apiVersion: v1
kind: Pod

metadata:
  name: toleration-demo

spec:
  containers:
    - name: nginx
      image: nginx:latest

  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "gpu"
      effect: "NoSchedule"
